package net.hedtech.banner.aip

import grails.test.*
import org.junit.Test
class ActionItemMaintenanceTests extends GrailsUnitTestCase {
 	def obj

protected void setUp() {
	super.setUp()
}


@Test
void testNullable()  { 
	ActionItemMaintenance obj = new ActionItemMaintenance(); 
	mockDomain(ActionItemMaintenance, [obj]) 
	obj.actionItemFolderId= null 
	obj.actionItemName= null 
	obj.actionItemTitle= null 
	obj.actionItemStatus= null 
	obj.actionItemPostingIndicator= null 
	obj.lastModified= null 
	obj.lastModifiedBy= null 

	obj.save() 
 
	assertTrue "nullable" == obj.errors['actionItemFolderId'] 
	assertTrue "nullable" == obj.errors['actionItemName'] 
	assertTrue "nullable" == obj.errors['actionItemTitle'] 
	assertTrue "nullable" == obj.errors['actionItemStatus'] 
	assertTrue "nullable" == obj.errors['actionItemPostingIndicator'] 
	assertTrue "nullable" == obj.errors['lastModified'] 
	assertTrue "nullable" == obj.errors['lastModifiedBy'] 
} 


@Test
void testMaxSize()  { 
	ActionItemMaintenance obj = new ActionItemMaintenance(); 
	mockDomain(ActionItemMaintenance, [obj]) 
	obj.actionItemFolderId= 0
	obj.actionItemName= "A"
	obj.actionItemName= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	obj.actionItemTitle= "A"
	obj.actionItemTitle= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	obj.actionItemStatus= "A"
	obj.actionItemStatus= "AA"
	obj.actionItemPostingIndicator= true
	obj.creator= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	obj.lastModified= new Date()
	obj.lastModifiedBy= "A"
	obj.lastModifiedBy= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	obj.dataOrigin= "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	obj.vpdiCode= "AAAAAAA"

	obj.save() 
 
	assertTrue "maxSize" == obj.errors['actionItemName']
	assertTrue "maxSize" == obj.errors['actionItemTitle']
	assertTrue "maxSize" == obj.errors['actionItemStatus']
	assertTrue "maxSize" == obj.errors['creator']
	assertTrue "maxSize" == obj.errors['lastModifiedBy']
	assertTrue "maxSize" == obj.errors['dataOrigin']
	assertTrue "maxSize" == obj.errors['vpdiCode']
}

@Test
void testSave()  { 
	ActionItemMaintenance obj = new ActionItemMaintenance(); 
	mockDomain(ActionItemMaintenance, [obj]) 
	obj.actionItemFolderId= 0
	obj.actionItemName= "A"
	obj.actionItemTitle= "A"
	obj.actionItemStatus= "A"
	obj.actionItemPostingIndicator= true
	obj.lastModified= new Date()
	obj.lastModifiedBy= "A"

	obj.save() 
 
	assertNotNull obj.id
} 


}